// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIbJQmJTfGIKZCUl5kYzTcRkrXVXI7q1E',
    appId: '1:195052316943:web:989c20b29d4da50176767a',
    messagingSenderId: '195052316943',
    projectId: 'fir-app-938bb',
    authDomain: 'fir-app-938bb.firebaseapp.com',
    storageBucket: 'fir-app-938bb.firebasestorage.app',
    measurementId: 'G-N6GDZKKX1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJnZn8ASLodl1GGMpiSO49y1B4alYcvo',
    appId: '1:195052316943:android:a1ca27138daa010276767a',
    messagingSenderId: '195052316943',
    projectId: 'fir-app-938bb',
    storageBucket: 'fir-app-938bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIu3eiPnyEqiz6jl8tHeSNgqJcDLSqTO4',
    appId: '1:195052316943:ios:06f00b1ca1cca99876767a',
    messagingSenderId: '195052316943',
    projectId: 'fir-app-938bb',
    storageBucket: 'fir-app-938bb.firebasestorage.app',
    iosBundleId: 'com.clarisco.clariscoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIu3eiPnyEqiz6jl8tHeSNgqJcDLSqTO4',
    appId: '1:195052316943:ios:06f00b1ca1cca99876767a',
    messagingSenderId: '195052316943',
    projectId: 'fir-app-938bb',
    storageBucket: 'fir-app-938bb.firebasestorage.app',
    iosBundleId: 'com.clarisco.clariscoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIbJQmJTfGIKZCUl5kYzTcRkrXVXI7q1E',
    appId: '1:195052316943:web:5263d3e1f004103776767a',
    messagingSenderId: '195052316943',
    projectId: 'fir-app-938bb',
    authDomain: 'fir-app-938bb.firebaseapp.com',
    storageBucket: 'fir-app-938bb.firebasestorage.app',
    measurementId: 'G-6LLTNGPY6M',
  );
}
